# Generated by Django 5.1.6 on 2026-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroupCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('recipient_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('is_compatible', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['donor_group', 'recipient_group'], name='core_bloodg_donor_g_8bb4e0_idx'), models.Index(fields=['recipient_group', 'is_compatible'], name='core_bloodg_recipie_631bf5_idx')],
                'unique_together': {('donor_group', 'recipient_group')},
            },
        ),
    ]
