# Generated by Django 5.1.6 on 2026-01-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bloodbank'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bloodbank',
            new_name='core_bloodb_city_e3e83e_idx',
            old_name='core_bloodbank_city_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='bloodbank',
            new_name='core_bloodb_latitud_25f4cc_idx',
            old_name='core_bloodbank_latitude_longitude_idx',
        ),
    ]
