# Generated by Django 5.1.6 on 2026-01-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donor_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donorstatistics',
            options={'ordering': ['-points', '-total_donations'], 'verbose_name_plural': 'Donor Statistics'},
        ),
        migrations.RenameIndex(
            model_name='donorfeedback',
            new_name='donations_d_donor_i_81a048_idx',
            old_name='donations_donorfeedback_donor_created_idx',
        ),
    ]
