# Generated by Django 5.1.6 on 2026-01-29 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_needed', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_needed', models.PositiveSmallIntegerField(default=1)),
                ('city', models.CharField(max_length=64)),
                ('area', models.CharField(blank=True, max_length=64)),
                ('hospital_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('sms_reply_token', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('sms', 'SMS')], default='web', max_length=8)),
                ('donor_consented_to_share_contact', models.BooleanField(default=False)),
                ('patient_contact_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_responses', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sos.sosrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['status', 'blood_group_needed', 'city'], name='sos_sosrequ_status_538d61_idx'),
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['created_at'], name='sos_sosrequ_created_1c6052_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['request', 'response'], name='sos_sosresp_request_262125_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['donor', 'response'], name='sos_sosresp_donor_i_447f34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosresponse',
            unique_together={('request', 'donor')},
        ),
    ]
