# Generated by Django 5.1.6 on 2026-01-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_sosrequest_priority'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sosrequest',
            new_name='sos_sosrequ_priorit_5604ca_idx',
            old_name='sos_sosrequest_priority_status_idx',
        ),
    ]
