# Generated by Django 5.1.6 on 2026-01-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_donor_i_5e42e0_idx',
            old_name='appointments_appointment_donor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_slot_id_49c7f3_idx',
            old_name='appointments_appointment_slot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentslot',
            new_name='appointment_date_e94451_idx',
            old_name='appointments_appointmentslot_date_city_status_idx',
        ),
    ]
